export const GET_ALL_ITEMS ="GET_ALL_ITEMS";
export const ADD_ITEM="ADD_ITEM";
export const DELETE_ITEM="DELETE_ITEM";
export const TOGGLE_COMPLETE_ITEM="TOGGLE_COMPLETE_ITEM";
export const UPDATE_ITEM="UPDATE_ITEM";
export const MOVE_ITEM="MOVE_ITEM";
export const DELETE_ALL_ITEMS="DELETE_ALL_ITEMS";